name: vandergugten
favicon: null
layout_spectrum: 0.3727518885862082
typography_spectrum: 0.2885483573190868
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#969591'
    - '#4376c7'
    - '#c5c4bf'
    - '#142539'
    - '#ffb385'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
